<?xml version="1.0" encoding="UTF-8"?>
<record_update table="sys_scope_privilege">
    <sys_scope_privilege action="INSERT_OR_UPDATE">
        <operation>execute</operation>
        <source_scope display_value="IT4IT">7938d16ddb64d300262950a45e9619c5</source_scope>
        <status>allowed</status>
        <sys_class_name>sys_scope_privilege</sys_class_name>
        <sys_created_by>212607632</sys_created_by>
        <sys_created_on>2018-02-28 13:48:17</sys_created_on>
        <sys_customer_update>false</sys_customer_update>
        <sys_id>450339f9dba85700262950a45e961985</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>ScriptableServiceError.setMessage</sys_name>
        <sys_package display_value="IT4IT" source="x_gege9_it4it">7938d16ddb64d300262950a45e9619c5</sys_package>
        <sys_policy/>
        <sys_replace_on_upgrade>false</sys_replace_on_upgrade>
        <sys_scope display_value="IT4IT">7938d16ddb64d300262950a45e9619c5</sys_scope>
        <sys_update_name>sys_scope_privilege_450339f9dba85700262950a45e961985</sys_update_name>
        <sys_updated_by>212607632</sys_updated_by>
        <sys_updated_on>2018-02-28 13:48:17</sys_updated_on>
        <target_name>ScriptableServiceError.setMessage</target_name>
        <target_scope display_value="Global">global</target_scope>
        <target_type>scriptable</target_type>
    </sys_scope_privilege>
</record_update>
